# ---------------------------------------------------------
# Workflow Name (shows up in GitHub Actions UI)
# ---------------------------------------------------------
name: Build and Test

# ---------------------------------------------------------
# Triggers: when does this workflow run?
# ---------------------------------------------------------
on:
  push:
    branches:
      - "**"        # Run on ALL branches (topic/feature, dev, main, etc.)
  pull_request:
    branches:
      - "main"      # Run when PR is opened against main

# ---------------------------------------------------------
# Jobs to run (can define multiple; here we just have build)
# ---------------------------------------------------------
jobs:
  build:
    runs-on: ubuntu-latest   # GitHub-hosted runner, Ubuntu is standard for Java builds

    steps:
      # -------------------------------
      # Step 1: Checkout repository code
      # -------------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------------------
      # Step 2: Set up JDK
      # -------------------------------
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin      # Temurin - OpenJDK build
          java-version: 21
          cache: maven               # Caches ~/.m2 to speed up future builds

      # -------------------------------
      # Step 3: Build & run tests
      # -------------------------------
      - name: Build with Maven
        run: mvn -B clean verify
        # mvn clean verify -> compiles, runs tests, validates the project
        # -B = batch mode (no interactive prompts, cleaner CI logs)
